language: generic

sudo: required
services: docker

before_install:
  - docker build -t gmk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gmk/react-test npm run test -- --coverage


after_success:
  - docker build -t gmk/multi-client ./client
  - docker build -t gmk/multi-nginx ./nginx
  - docker build -t gmk/multi-server ./server
  - docker build -t gmk/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gmk/multi-client
  - docker push gmk/multi-nginx
  - docker push gmk/multi-server
  - docker push gmk/multi-worker